# Generated by Django 6.0 on 2025-12-16 03:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReciepeData',
            fields=[
                ('reciepe_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reciepe_name', models.CharField(max_length=150)),
                ('reciepe_description', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
